# Generated by Django 3.1.7 on 2021-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawreport',
            name='parsed_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
