# Generated by Django 3.2 on 2021-04-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedreport',
            name='temp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
