# Generated by Django 3.1.7 on 2021-04-21 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_schema', '0002_rawreport_parsed_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawreport',
            name='report_type',
        ),
    ]
