# Generated by Django 3.2 on 2021-04-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_schema', '0002_generatedreport_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='temp',
        ),
    ]
