# Generated by Django 3.2 on 2021-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_schema', '0003_remove_rawreport_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='path',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='json_schema',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
