# Generated by Django 3.1.7 on 2021-04-07 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_schema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generatedreport',
            name='url',
        ),
        migrations.RemoveField(
            model_name='generatedreport',
            name='user',
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='created_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='path',
            field=models.FilePathField(default='/', path='/'),
            preserve_default=False,
        ),
    ]
