# Generated by Django 3.1.7 on 2021-04-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_schema', '0002_auto_20210406_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='path',
            field=models.FilePathField(allow_folders=True, path='/'),
        ),
    ]
