# Generated by Django 3.1.7 on 2021-04-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cik', models.CharField(max_length=50)),
            ],
        ),
    ]
